#!/usr/bin/bash
#
# pocket2csv
#
# Copyright (c) 2020 Christopher Crawford.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Modification History:
#
# - 26 Aug 2024 by Chris K.Y. Fung:
#   - Command-Line Flags:
#     - Added new flags `-k` (consumer key) and `-t` (access token) for command-line input.
#     - Updated script logic to handle these flags, skipping unnecessary prompts or OAuth steps when the flags are used.
#   - Usability Improvements:
#     - Streamlined user interactions by reducing redundant prompts and improving overall script usability.
#
# - 20 Mar 2025 by Chris K.Y. Fung:
#   - Pagination Support:
#     - Implemented pagination logic to fetch bookmarks in batches of 30 items from the Pocket API.
#     - Used a `while` loop with `count` and `offset` parameters to handle multiple pages efficiently.
#     - Added real-time progress tracking, displaying download progress as a percentage.
#   - JSON Processing Enhancements:
#     - Enhanced JSON processing logic to gracefully handle null values using `select(. != null)`.
#     - Optimized the conversion of fields such as `item_id`, `favorite`, and `time_added` to ensure type consistency and avoid errors.
#
# - 21 Mar 2025 by Chris K.Y. Fung:
#   - CSV Generation Fixes and Improvements:
#     - Refactored the logic for dynamically generating column titles and appending data rows to the CSV file.
#     - Ensured proper handling of null values and alignment with the defined column keys.
#
# Original copyright and license information remains intact.

# Initialize variables
CONSUMER_KEY=""
TOKEN=""

read -r -d '' LOGO <<'EOF'
...                   _          _    ___                   
                     | |        | |  |__ \                  
  _ __    ___    ___ | | __ ___ | |_    ) | ___  ___ __   __
 | '_ \  / _ \  / __|| |/ // _ \| __|  / / / __|/ __|\ \ / /
 | |_) || (_) || (__ |   <|  __/| |_  / /_| (__ \__ \ \ V / 
 | .__/  \___/  \___||_|\_\\___| \__||____|\___||___/  \_/  
 | |                                                        
 |_|                                                       
...   

EOF
echo ""
echo "$LOGO"
echo ""
echo ""

while getopts "k:t:" opt; do
 case $opt in
  k)
   CONSUMER_KEY=$OPTARG
   ;;
  t)
   MY_ACCESS_TOKEN=$OPTARG
   ;;
 esac
done

if [ "$CONSUMER_KEY" == "" ]
then
  read -p '[1] Enter Your Pocket API Consumer Key: ' CONSUMER_KEY

  read -r -d '' MY_DATA <<EOF
{
"consumer_key":"$CONSUMER_KEY",
"redirect_uri":"https://getpocket.com"
}
EOF
fi

if [ "$MY_ACCESS_TOKEN" == "" ]
then
  MY_CODE=$(
  curl \
    --silent \
    --request POST \
    --url https://getpocket.com/v3/oauth/request \
    --header 'content-type: application/json; charset=UTF-8' \
    --header 'x-accept: application/json' \
    --data "$MY_DATA" \
  | jq -r .code)
  
  echo "[2] Visit this link in a browser:"
  echo ""
  echo "https://getpocket.com/auth/authorize?request_token=$MY_CODE&redirect_uri=https://getpocket.com"
  echo ""
  echo "[3] Login to Pocket (if not already logged in)."
  echo "[4] Click the Authorize button."
  echo "[!] "
  echo "[!] DO NOT CONTINUE UNTIL YOU DO [2], [3], [4] !"
  echo "[!] OTHERWISE THIS SCRIPT WILL FAIL. ☠"
  echo "[!] "
  read -p "[5] Press any key to continue (CTRL-C to quit)... "

  read -r -d '' MY_DATA <<EOF
  {
  "consumer_key":"$CONSUMER_KEY",
  "code":"$MY_CODE"
  }
EOF

  MY_ACCESS_TOKEN=$(
  curl \
    --silent \
    --request POST \
    --url https://getpocket.com/v3/oauth/authorize \
    --header 'content-type: application/json; charset=UTF-8' \
    --header 'x-accept: application/json' \
    --data "$MY_DATA" \
  | jq -r .access_token)

  echo "Token: $MY_ACCESS_TOKEN"
fi

read -r -d '' MY_DATA <<EOF
{
"state": "all",
"sort": "newest",
"detailType": "complete",
"consumer_key":"$CONSUMER_KEY",
"access_token":"$MY_ACCESS_TOKEN",
"count": "30",
"offset": "0",
"total": "1"
}
EOF

echo "[+] Downloading Pocket bookmarks to bookmarks.json..."

# Pagination logic to handle multiple pages of bookmarks from the Pocket API
# - Fetches data in batches of 30 items (controlled by "count").
# - Increments the "offset" after each request to retrieve the next page.
# - Continues until all pages are downloaded (tracked by "total" and "offset").
TOTAL=1
OFFSET=0
> bookmarks.json

while [ $OFFSET -lt $TOTAL ]; do
  RESPONSE=$(curl \
    --silent \
    --request POST \
    --url https://getpocket.com/v3/get \
    --header 'content-type: application/json' \
    --data "$MY_DATA")

  echo "$RESPONSE" | jq '.list | select(. != null) | .[]' >> bookmarks.json

  TOTAL=$(echo "$RESPONSE" | jq '.total // 0' | bc)
  OFFSET=$((OFFSET + 30))

  # Calculate and display progress
  PROGRESS=$((OFFSET * 100 / TOTAL))
  echo -n -e "[+] Progress: $PROGRESS% ($OFFSET/$TOTAL)\033[0K\r"

  read -r -d '' MY_DATA <<EOF
{
"state": "all",
"sort": "newest",
"detailType": "complete",
"consumer_key":"$CONSUMER_KEY",
"access_token":"$MY_ACCESS_TOKEN",
"count": "30",
"offset": "$OFFSET",
"total": "1"
}
EOF
done

echo "[+] All pages downloaded. Creating intermediate file bookmarks-tmp.json..."

# Process the downloaded bookmarks.json file into an intermediate format
# - Handles null values gracefully using `select(. != null)` to avoid errors.
# - Converts fields like item_id, favorite, and time_added to appropriate types.
jq -s '.' bookmarks.json \
| jq 'map(
  if .tags == null then .tags = {} else .tags = .tags end
  | .item_id = (.item_id | select(. != null) | tonumber)
  | .favorite = (.favorite | select(. != null) | tonumber)
  | .has_video = (.has_video | select(. != null) | tonumber)
  | .has_image = (.has_image | select(. != null) | tonumber)
  | .word_count = (.word_count | select(. != null) | tonumber)
  | .time_added = (.time_added | select(. != null) | tonumber | todate)
  | .year_added = (.time_added | select(. != null) | split("T") | .[0] | split("-") | .[0] | tonumber)
  | .month_added = (.time_added | select(. != null) | split("T") | .[0] | split("-") | .[1] | tonumber)
  | .day_added = (.time_added | select(. != null) | split("T") | .[0] | split("-") | .[2] | tonumber)
  | .hour_added = (.time_added | select(. != null) | split("T") | .[1] | split(":") | .[0] | tonumber)
  | .tags = (.tags | select(. != null) | keys)
  | .ntags = (.tags | select(. != null) | length)
  | .tags = (.tags | select(. != null) | join(" AND "))
  | .given_domain = (.given_url | select(. != null) | split ("/") | .[2])
  | .n_given_domain = (.given_url | select(. != null) | split (".") | length)
  | .resolved_domain = (.resolved_url | select(. != null) | split ("/") | .[2])
  | .n_resolved_domain = (.resolved_url | select(. != null) | split (".") | length)
  | .n_domain_equal = (.n_given_domain == .n_resolved_domain)
  | .given_tld1 = (.given_domain | select(. != null) | tostring | split(".") | .[length-1])
  | .given_tld2 = (.given_domain | select(. != null) | tostring | split(".") | .[length-2])
  | .resolved_tld1 = (.resolved_domain | select(. != null) | tostring | split(".") | .[length-1])
  | .resolved_tld2 = (.resolved_domain | select(. != null) | tostring | split(".") | .[length-2])
  | .titles_match = (.given_title == .resolved_title)
  | .urls_match = (.given_url == .resolved_url)
  | .domains_match = (.given_domain == .resolved_domain)
  | .excerpt = (.excerpt | select(. != null) | gsub("[\\n\\t]"; ""))
  | .given_title = (.given_title | select(. != null) | gsub("[\\n\\t]"; ""))
)' > bookmarks-tmp.json

echo "[+] Converting bookmarks-tmp.json to bookmarks.csv..."

# Define column keys
COLUMN_KEYS=(item_id time_added given_title resolved_url tags favorite has_video has_image word_count year_added month_added day_added hour_added given_domain resolved_domain titles_match urls_match domains_match excerpt)

# Dynamically generate column titles from the keys
COLUMN_TITLES=$(printf "%s," "${COLUMN_KEYS[@]}" | sed 's/,$//')

# Write column titles to the CSV file
echo "$COLUMN_TITLES" > bookmarks.csv

# Append data rows to the CSV file corresponding to the column keys
jq -r --argjson keys "$(printf '%s\n' "${COLUMN_KEYS[@]}" | jq -R . | jq -s .)" '
  map(select(.item_id != null and .resolved_url != null)) | .[] | 
  [$keys[] as $key | .[$key]] | @csv
' bookmarks-tmp.json >> bookmarks.csv

echo "[+] Done."
